### ISSUE TITLE
practica-de-entrevista-cuestionarios

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-team-desarrollosoftware#1]
[RequisitosdeSistemadeSoftware.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-team-desarrollosoftware/files/13220760/RequisitosdeSistemadeSoftware.pdf)

**Comment by Arlet04** [comment]
Buen trabajo 30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
