### ISSUE TITLE
Reporte de practica 7

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-team-desarrollosoftware#3]
[REPORTE DE PRACTICA 7.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-team-desarrollosoftware/files/13311394/REPORTE.DE.PRACTICA.7.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by JeroRoque** [comment]
28.9/30

**Comment by josealfredo79** [comment]
bien hecho y revisado...
